### PR TITLE
Gaming Rgb for human player

### PR DESCRIPTION
**Pull request by Connerbruner**
Before issuing a pull request, please see the contributing page.

### CODE REVIEW

**Review by Cjh4444 — CHANGES_REQUESTED** [review]
there's no code here

**Review by Cjh4444 — CHANGES_REQUESTED** [review]
don't change the sdk version

**Review by sirpoetvic — DISMISSED** [review]
Don't change the SDK version, go back to 29.

**Review by Cjh4444 — CHANGES_REQUESTED** [review]
compileSdk -> compileSdkVersion

**Comment by sirpoetvic** [comment]
> compileSdk -> compileSdkVersion

I think it's deprecated? At least that's what it says in my code, idk.

**Review by Cjh4444 — APPROVED** [review]

**Pull request merged**
